# Global configuration for the Crypto Premarket Alert Bot.
# Values here are placeholders and should be tuned before production use.

app:
  venue_poll_interval_seconds: 60
  debounce_seconds: 30
  min_notional_usdt: 100.0
  spread_threshold_percent: 2.0

venues:
  mexc:
    enabled: true
    symbols: ["TNSR_USDT"]
  whales_market:
    enabled: true
    symbols: ["TNSR"]
  bitget:
    enabled: false
  bybit:
    enabled: false
  hyperliquid:
    enabled: false
  binance:
    enabled: false

telegram:
  enabled: false
  chat_id: ${TELEGRAM_CHAT_ID}
  alert_prefix: "[Premarket Alert]"

logging:
  level: INFO
  file: logs/bot.log
